import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import tailwindcss from '@tailwindcss/vite';
import { resolve } from 'path';
import { copyFileSync } from 'fs';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
	const prod = mode === 'production';

	return {
		plugins: [
			svelte(),
			tailwindcss(),
			// Custom plugin to copy manifest.json to build folder
			{
				name: 'copy-manifest',
				writeBundle() {
					copyFileSync('manifest.json', 'build/manifest.json');
				}
			}
		],
		build: {
			lib: {
				entry: resolve(__dirname, 'src/main.ts'), // Adjusted to src/main.ts
				name: 'ObsigentPlugin', // Changed to a more descriptive name
				fileName: () => `main.js`, // Output main.js for Obsidian, format removed for single file
				formats: ['cjs'], // Obsidian plugins typically use CJS
			},
			rollupOptions: {
				external: [
					'obsidian',
					'electron',
					'@codemirror/autocomplete',
					'@codemirror/collab',
					'@codemirror/commands',
					'@codemirror/language',
					'@codemirror/lint',
					'@codemirror/search',
					'@codemirror/state',
					'@codemirror/view',
					'@lezer/common',
					'@lezer/highlight',
					'@lezer/lr',
					// Add other built-in Node modules if necessary, Vite handles many by default
				],
				output: {
					// Ensures that the output is a single file, which is typical for Obsidian plugins
					// and mimics the esbuild behavior.
					manualChunks: undefined,
					// Banner to match esbuild config
					banner: `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/`,
					// Customize CSS file name
					assetFileNames: (assetInfo) => {
						if (assetInfo.name?.endsWith('.css')) {
							return 'styles.css';
						}
						return '[name].[ext]';
					},
				},
			},
			sourcemap: prod ? false : 'inline',
			minify: prod,
			outDir: './build',
		},
		// Resolve aliases from tsconfig.json (though svelte-preprocess handles this for Svelte)
		resolve: {
			alias: {
				'@': resolve(__dirname, './src'),
				'$lib': resolve(__dirname, './src/lib'),
			},
		},
	};
});
